services:
  maxpower:
    image: awaescher/maxpower:latest
    container_name: maxpower
    ports:
      - "8080:8080"
    env_file:
      - maxpower.env
    restart: always

  # I found that the inverters turned inaccessible after ~24 hours of running MaxPower.
  # Strangely enough, only restarting the MaxPower-container fixed it.
  # I checked the code but could not find any leaks or possible connection issues.
  # That's why I went with the crowbar tactic and added this additional docker container
  # that restarts the MaxPower-container regularly. You might need it too.
  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          echo "Restarting MaxPower ..."
          docker restart maxpower
          sleep 3600
        done
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    command:
      - '--storage.tsdb.retention.time=30d' # keep data 30 days - all the values below are just defaults that need to be defined if commands are used
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus/data:/prometheus
      - ./volumes/prometheus/etc:/etc
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9091:3000"
    user: "0"
    links:
      - prometheus
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    restart: always
