name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch all history for all tags and branches
      run: |
        git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git fetch --prune --unshallow

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag awaescher/maxpower:${{steps.gitversion.outputs.semVer}} --tag awaescehr/maxpower:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name != 'pull_request'
          
    - name: Push the Docker image
      run: docker push awaescher/maxpower:${{steps.gitversion.outputs.semVer}}
      if: github.event_name != 'pull_request'

    - name: Push the Docker image latest
      run: docker push awaescher/maxpower:latest
      if: github.event_name != 'pull_request'

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{steps.gitversion.outputs.semVer}}
        name: Release ${{steps.gitversion.outputs.semVer}}
      if: github.event_name != 'pull_request'
